# Generated by Django 6.0 on 2025-12-11 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='categoria_principal',
            field=models.CharField(blank=True, help_text='Categoria principal: Revestimento 3D cimentício, Artefatos Cimentícios, Cube Concreto, Linha Jardim, Elemento Vazado Cobogó', max_length=100),
        ),
        migrations.AlterField(
            model_name='produto',
            name='categoria',
            field=models.CharField(blank=True, help_text='Subcategoria: Amadeirados, Tijolinho, Mosaicos, etc.', max_length=100),
        ),
    ]
