# Generated by Django 6.0 on 2025-12-11 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_produto_categoria_principal_alter_produto_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='cor',
            field=models.CharField(blank=True, help_text='Ex: Cor natural (concreto cinza)', max_length=100),
        ),
        migrations.AddField(
            model_name='produto',
            name='dimensoes',
            field=models.CharField(blank=True, help_text='Ex: 30x30x2cm', max_length=100),
        ),
        migrations.AddField(
            model_name='produto',
            name='especificacoes',
            field=models.TextField(blank=True, help_text='Especificações adicionais, uma por linha'),
        ),
        migrations.AddField(
            model_name='produto',
            name='unidade_venda',
            field=models.CharField(blank=True, help_text='Ex: Vendido o M²', max_length=100),
        ),
    ]
