# Generated by Django 5.2.5 on 2025-12-21 04:20

import django.db.models.deletion
from django.db import migrations, models


def migrate_categoria_principal(apps, schema_editor):
    Produto = apps.get_model('core', 'Produto')
    CategoriaPrincipal = apps.get_model('core', 'CategoriaPrincipal')

    # Get unique categoria_principal values
    unique_cats = Produto.objects.exclude(categoria_principal__isnull=True).exclude(categoria_principal='').values_list('categoria_principal', flat=True).distinct()

    for cat_name in unique_cats:
        cat, created = CategoriaPrincipal.objects.get_or_create(
            nome=cat_name,
            defaults={'ordem': 0, 'ativo': True}
        )
        # Update produtos
        Produto.objects.filter(categoria_principal=cat_name).update(categoria_principal=cat.id)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_add_produto_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoriaprincipal',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='mensagemcontato',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.RunPython(migrate_categoria_principal, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='produto',
            name='categoria_principal',
            field=models.ForeignKey(blank=True, help_text='Categoria principal', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.categoriaprincipal'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='subcategoria',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
