# Generated by Django 6.0 on 2026-02-18 03:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_produto_imagem_alter_produto_imagem_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='subcategoria',
            field=models.ForeignKey(blank=True, help_text='Subcategoria associada (quando aplicável)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produtos', to='core.subcategoria'),
        ),
    ]
