# Generated by Django 6.0.4 on 2026-04-22 13:39

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_produto_subcategoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Destaque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('imagem', 'Imagem'), ('video', 'Vídeo')], default='imagem', max_length=10, verbose_name='Tipo de Mídia')),
                ('titulo', models.CharField(blank=True, max_length=200, verbose_name='Título (ex: Revestimento em Tijolos)')),
                ('subtitulo', models.CharField(blank=True, max_length=200, verbose_name='Subtítulo (ex: Perfeito para sua sala)')),
                ('arquivo', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Arquivo (Foto ou Vídeo)')),
                ('link_externo', models.CharField(blank=True, max_length=500, verbose_name='Link Externo (caso não seja produto)')),
                ('ordem', models.IntegerField(default=0, verbose_name='Ordem')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('produto_link', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.produto', verbose_name="Produto para 'Saiba Mais'")),
            ],
            options={
                'verbose_name': 'Destaque',
                'verbose_name_plural': 'Destaques',
                'ordering': ['ordem', 'created_at'],
            },
        ),
    ]
